#!/usr/bin/env python

import base64, httplib, json, os, sys
from urlparse import urlparse

# =======================================================================================================================
# main
# =======================================================================================================================
if __name__ == '__main__':

    obRUrl = urlparse(os.environ.get('RANCHER_URL'))
    rAccessKey = os.environ.get('RANCHER_ACCESS_KEY')
    rSecretKey = os.environ.get('RANCHER_SECRET_KEY')
    rLBServiceId = os.environ.get('RANCHER_LB_SERVICE_ID')
    rBGVariants = json.loads(os.environ.get('RANCHER_BG_VARIANTS'))
    rBGHostname = os.environ.get('RANCHER_BG_HOSTNAME')

    def discovery_by_port_rules(pr, ls):
        for rule in pr:
            if rule['protocol'] == 'http' and rule['hostname'] == rBGHostname:
                for sService, serviceId in ls.iteritems():
                    if serviceId == rule['serviceId']:
                        [project, service] = sService.split('/')
                        return project

    def discovery_by_linked_services(ls):
        for sService, idService in ls.items():
            [project, service] = sService.split('/')
            if project in rBGVariants:
                res = list(set(rBGVariants).difference([project]))[0]
                return res

    conn = httplib.HTTPSConnection(obRUrl.netloc)

    headers = {
        "Accept": "application/json",
        "Authorization": "Basic " + base64.b64encode((rAccessKey + ':' + rSecretKey).encode('ascii')).decode("utf-8")
    }

    conn.request("GET", obRUrl.path + "/loadbalancerservices/" + rLBServiceId, None, headers)

    response = conn.getresponse()
    if response.status == 200:
        sLbMeta = response.read()
        lbMeta = json.loads(sLbMeta.decode("utf-8"))
        portRules = lbMeta['lbConfig']['portRules']
        linkedServices = lbMeta['linkedServices']

        nextProject = None
        if not nextProject:
            nextProject = discovery_by_port_rules(portRules, linkedServices)
        if not nextProject:
            nextProject = discovery_by_linked_services(linkedServices)
        elif not nextProject:
            nextProject = rBGVariants[0]

        print(nextProject)

    else:
        exitMessage = obRUrl.netloc + ' response: ' + str(response.status) + ' ' + response.reason
        print(exitMessage)
        sys.exit(1)
